const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getPathForFile: (file) => webUtils.getPathForFile(file),
  onOcrProgress: (callback) => ipcRenderer.on('ocr-progress', (event, data) => callback(data)),
  saveInvoice: (invoiceData) => ipcRenderer.invoke('save-invoice', invoiceData),
  openInvoicesFolder: () => ipcRenderer.invoke('open-invoices-folder'),
  downloadInvoicePdf: (data) => ipcRenderer.invoke('download-invoice-pdf', data),
  readInvoicePdf: (filePath) => ipcRenderer.invoke('read-invoice-pdf', filePath),
  copyFileToClipboard: (filePath) => ipcRenderer.invoke('copy-file-to-clipboard', filePath),
  openInvoicePdf: (data) => ipcRenderer.invoke('open-invoice-pdf', data),
  getInvoices: () => ipcRenderer.invoke('get-invoices'),
  getInvoiceItems: (invoiceId) => ipcRenderer.invoke('get-invoice-items', invoiceId),
  getAllInvoiceItems: () => ipcRenderer.invoke('get-all-invoice-items'),
  deleteInvoice: (invoiceId) => ipcRenderer.invoke('delete-invoice', invoiceId),
  deleteOrder: (orderId) => ipcRenderer.invoke('delete-order', orderId),
  updateOrder: (data) => ipcRenderer.invoke('update-order', data),
  deleteBill: (billId) => ipcRenderer.invoke('delete-bill', billId),
  saveOrder: (data) => ipcRenderer.invoke('save-order', data),
  saveBill: (data) => ipcRenderer.invoke('save-bill', data),
  getOrders: () => ipcRenderer.invoke('get-orders'),
  getOrderItems: (orderId) => ipcRenderer.invoke('get-order-items', orderId),
  getBills: (status) => ipcRenderer.invoke('get-bills', status),
  getBillItems: (billId) => ipcRenderer.invoke('get-bill-items', billId),
  updateBillStatus: (billId, status) => ipcRenderer.invoke('update-bill-status', { billId, status }),
  getAnalytics: () => ipcRenderer.invoke('get-analytics'),
  getNextInvoiceNumber: () => ipcRenderer.invoke('get-next-invoice-number'),
  updateCustomerDetails: (data) => ipcRenderer.invoke('update-customer-details', data),
  printInvoice: (data) => ipcRenderer.invoke('print-invoice', data),
  getPrinters: () => ipcRenderer.invoke('get-printers'),
  clearCustomerDues: (name, phone) => ipcRenderer.invoke('clear-customer-dues', { name, phone }),
  downloadOrderPdf: (data) => ipcRenderer.invoke('download-order-pdf', data),
  readOrderPdf: (filePath) => ipcRenderer.invoke('read-order-pdf', filePath),
  openOrdersFolder: () => ipcRenderer.invoke('open-orders-folder'),
  openPurchaseBillsFolder: () => ipcRenderer.invoke('open-purchase-bills-folder'),
  getNextOrderNumber: () => ipcRenderer.invoke('get-next-order-number'),
  ocrBillPhoto: (imagePath) => ipcRenderer.invoke('ocr-bill-photo', imagePath),
  generateBillPdf: (data) => ipcRenderer.invoke('generate-bill-pdf', data),
  downloadBillPdf: (data) => ipcRenderer.invoke('download-bill-pdf', data),
  clearBillDues: (billId) => ipcRenderer.invoke('clear-bill-dues', billId),
  deleteBill: (billId) => ipcRenderer.invoke('delete-bill', billId),
  readBillPdf: (filePath) => ipcRenderer.invoke('read-order-pdf', filePath),
  getDueBillsByDate: () => ipcRenderer.invoke('get-due-bills-by-date')
});
